server:
  port: 9093
  servlet:
    context-path: /pocarquitetura

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
    eureka-server-connect-timeout-seconds: 60
  server:
    wait-time-in-ms-when-sync-empty: 30000

spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

zuul:
    routes:
        pessoas:
            path: /pessoas/**
            url: http://localhost:9091/pocarquitetura/pessoas
         
        